/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mgpatient;

import mgpatient.ui.MainUI;

public class App {
    public static void main(String[] args) {
        new MainUI().start();
    }
}
